// <auto-generated />
using System;
using MDGriphe.Experiments.Lumia950.WebHost.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MDGriphe.Experiments.Lumia950.WebHost.Migrations
{
    [DbContext(typeof(VisitorsDbContext))]
    [Migration("20201109214039_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("MDGriphe.Experiments.Lumia950.WebHost.Core.Data.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Visit","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
